---
# Project information
site_name: SIG/FastTrack Wiki
site_url: https://sig-fasttrack.rocky.page
site_description: >-
  FastTrack, as an ode to a past CentOS repository of a similar name, is a SIG to attempt to provide the following:

  * Fixes, customizations, improvements to packages that the community would like to see
  * This also includes doing backports of patches that may not be released by our upstreams to address any type of bugs
  * Potential packages that could potentially make it to CentOS Stream or EPEL
  * Newer versions of software that override the base repositories that would likely never land in RHEL, CentOS Stream, or EPEL

# Repository
repo_url: https://git.resf.org/sig_fasttrack/wiki
repo_name: sig_fasttrack/wiki
edit_uri: _edit/main/docs/

# Copyright
copyright: Copyright &copy; 2023 Rocky Enterprise Software Foundation

# Configuration
theme:
  name: material
  logo: assets/icon-white.svg
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  highlightjs: true
  hljs_languages:
    - bash
    - perl
    - python
    - yaml
  features:
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.path
    - search.highlight
    - search.suggest
    - toc.integrate
    - content.action.edit

# Plugins
plugins:
  - autolinks
  - awesome-pages
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
  - search

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - pymdownx.details # this allows collapsible attributions
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
